apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dummy-dev
  #namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dummy-dev
  chart:
    name: fluent/fluent-bit
    git: git@github.com:helm/charts
    path: stable/fluent-bit
    ref: master
  values:
    image:
      tag: 1.5
    replicaCount: 1